
import uvicorn
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Dict, Optional
import uuid

app = FastAPI(title="A2A Agent Backend")

# --- Shared Schemas ---
class Task(BaseModel):
    task_id: str
    goal: str
    context: Dict[str, str] = {}
    required_capabilities: List[str] = []

class TaskStatus(BaseModel):
    task_id: str
    status: str  # "pending", "running", "completed", "failed"
    artifacts: List[str] = []
    metadata: Dict[str, str] = {}

# In-memory store for demo purposes
task_store: Dict[str, TaskStatus] = {}

# --- Helper to simulate A2A Orchestration ---
def build_mri_drift_task(goal: str, context: Dict[str, str]) -> Task:
    return Task(
        task_id=f"MRI-{uuid.uuid4().hex[:8]}",
        goal=goal,
        context=context,
        required_capabilities=["mri_logs", "clinical_protocol"]
    )

@app.post("/mri_drift_task", response_model=List[TaskStatus])
async def run_mri_drift_task(req: dict):
    # This simulates the Orchestrator calling a Planner and Executor
    initial_task = build_mri_drift_task(req["goal"], req["context"])
    
    # Mocked steps generated by a Planner Agent
    steps = [
        TaskStatus(
            task_id=f"{initial_task.task_id}.1",
            status="completed",
            metadata={"executed_step": "fetch_performance_logs", "agent": "executor_1"}
        ),
        TaskStatus(
            task_id=f"{initial_task.task_id}.2",
            status="completed",
            metadata={"executed_step": "analyze_drift_trend", "agent": "executor_2"}
        )
    ]
    
    # Save the main task status
    task_store[initial_task.task_id] = TaskStatus(task_id=initial_task.task_id, status="completed")
    return steps

@app.get("/status/{task_id}", response_model=TaskStatus)
async def get_status(task_id: str):
    if task_id not in task_store:
        raise HTTPException(status_code=404, detail="Task not found")
    return task_store[task_id]

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
